2014/02/26 06:21:45 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('project/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/trackstar/index.php?r=project/admin
HTTP_REFERER=http://localhost/trackstar/index.php?r=project/view&id=1
---
2014/02/28 06:44:07 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php:194)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): IssueController->filterAccessControl()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): IssueController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): IssueController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\TrackStar\index.php(13): CWebApplication->run()
REQUEST_URI=/trackstar/index.php?r=issue/create
in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php (194)
in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php (218)
in C:\xampp\htdocs\TrackStar\index.php (13)
2014/02/28 06:46:07 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php:194)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): IssueController->filterAccessControl()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): IssueController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): IssueController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\TrackStar\index.php(13): CWebApplication->run()
REQUEST_URI=/trackstar/index.php?r=issue/create
in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php (194)
in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php (218)
in C:\xampp\htdocs\TrackStar\index.php (13)
2014/02/28 06:46:15 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php:194)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): IssueController->filterAccessControl()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): IssueController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): IssueController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\TrackStar\index.php(13): CWebApplication->run()
REQUEST_URI=/trackstar/index.php?r=issue/create
in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php (194)
in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php (218)
in C:\xampp\htdocs\TrackStar\index.php (13)
2014/02/28 06:51:17 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php:196)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): IssueController->filterAccessControl()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): IssueController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): IssueController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\TrackStar\index.php(13): CWebApplication->run()
REQUEST_URI=/trackstar/index.php?r=issue/create
in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php (196)
in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php (223)
in C:\xampp\htdocs\TrackStar\index.php (13)
2014/02/28 06:52:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested project does not exist.' in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php:206
Stack trace:
#0 C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php(229): IssueController->loadProject(NULL)
#1 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): IssueController->filterProjectContext(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('issue/create')
#11 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#12 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/trackstar/index.php?r=issue/create
HTTP_REFERER=http://localhost/trackstar/index.php?r=issue
---
2014/02/28 06:53:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The request project do not exist.' in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php:198
Stack trace:
#0 C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php(229): IssueController->loadProject(NULL)
#1 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): IssueController->filterProjectContext(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('issue/create')
#11 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#12 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/trackstar/index.php?r=issue/create
HTTP_REFERER=http://localhost/trackstar/index.php?r=issue
---
2014/02/28 06:53:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested project does not exist.' in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php:198
Stack trace:
#0 C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php(221): IssueController->loadProject(NULL)
#1 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): IssueController->filterProjectContext(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('issue/create')
#11 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#12 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/trackstar/index.php?r=issue/create
HTTP_REFERER=http://localhost/trackstar/index.php?r=issue
---
2014/02/28 06:54:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested project does not exist.' in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php:198
Stack trace:
#0 C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php(221): IssueController->loadProject(NULL)
#1 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): IssueController->filterProjectContext(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('issue/create')
#11 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#12 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/trackstar/index.php?r=issue/create
HTTP_REFERER=http://localhost/trackstar/index.php?r=issue
---
2014/02/28 06:56:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested project does not exist.' in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php:198
Stack trace:
#0 C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php(221): IssueController->loadProject(NULL)
#1 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): IssueController->filterProjectContext(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('issue/create')
#11 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#12 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/trackstar/index.php?r=issue/create
HTTP_REFERER=http://localhost/trackstar/index.php?r=issue
---
2014/03/01 07:39:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested project does not exist.' in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php:198
Stack trace:
#0 C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php(221): IssueController->loadProject(NULL)
#1 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): IssueController->filterProjectContext(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('issue/create')
#11 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#12 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/trackstar/index.php?r=issue/create
HTTP_REFERER=http://localhost/trackstar/index.php?r=issue/admin
---
2014/03/12 19:46:42 [error] [php] Missing argument 1 for ProjectController::loadModel(), called in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php on line 57 and defined (C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php:164)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#7 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ProjectController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#13 C:\xampp\htdocs\TrackStar\index.php(13): CWebApplication->run()
REQUEST_URI=/trackstar/index.php?r=project/view&id=1
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (164)
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (57)
in C:\xampp\htdocs\TrackStar\index.php (13)
2014/03/12 19:47:55 [error] [php] Object of class Project could not be converted to string (C:\xampp\htdocs\yii\framework\db\CDbCommand.php:274)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\schema\CDbCommandBuilder.php(177): CMysqlCommandBuilder->bindValues()
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1546): CMysqlCommandBuilder->createCountCommand()
#2 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(179): Issue->count()
#3 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#4 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(129): CActiveDataProvider->getTotalItemCount()
#5 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#6 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(107): CActiveDataProvider->getData()
#7 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(203): CListView->init()
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(172): ProjectController->createWidget()
#10 C:\xampp\htdocs\TrackStar\protected\views\project\view.php(39): ProjectController->widget()
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#12 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): ProjectController->renderInternal()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(869): ProjectController->renderFile()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(782): ProjectController->renderPartial()
#15 C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php(67): ProjectController->render()
#16 unknown(0): ProjectController->actionView()
#17 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#18 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#19 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#20 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#21 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#23 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#26 C:\xampp\htdocs\yii\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#27 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ProjectController->run()
#28 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#29 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#30 C:\xampp\htdocs\TrackStar\index.php(13): CWebApplication->run()
REQUEST_URI=/trackstar/index.php?r=project/view&id=1
in C:\xampp\htdocs\TrackStar\protected\views\project\view.php (39)
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (67)
in C:\xampp\htdocs\TrackStar\index.php (13)
2014/03/12 19:55:49 [error] [php] Missing argument 1 for ProjectController::loadModel(), called in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php on line 57 and defined (C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php:164)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#7 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ProjectController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#13 C:\xampp\htdocs\TrackStar\index.php(13): CWebApplication->run()
REQUEST_URI=/trackstar/index.php?r=project/view&id=1
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (164)
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (57)
in C:\xampp\htdocs\TrackStar\index.php (13)
2014/03/12 19:56:30 [error] [php] Missing argument 1 for ProjectController::loadModel(), called in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php on line 57 and defined (C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php:164)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#7 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ProjectController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#13 C:\xampp\htdocs\TrackStar\index.php(13): CWebApplication->run()
REQUEST_URI=/trackstar/index.php?r=project/view&id=1
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (164)
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (57)
in C:\xampp\htdocs\TrackStar\index.php (13)
2014/03/12 19:56:36 [error] [php] Missing argument 1 for ProjectController::loadModel(), called in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php on line 57 and defined (C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php:164)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#7 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ProjectController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#13 C:\xampp\htdocs\TrackStar\index.php(13): CWebApplication->run()
REQUEST_URI=/trackstar/index.php?r=project/view&id=1
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (164)
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (57)
in C:\xampp\htdocs\TrackStar\index.php (13)
2014/03/12 19:56:38 [error] [php] Missing argument 1 for ProjectController::loadModel(), called in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php on line 57 and defined (C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php:164)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#7 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ProjectController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#13 C:\xampp\htdocs\TrackStar\index.php(13): CWebApplication->run()
REQUEST_URI=/trackstar/index.php?r=project/view&id=1
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (164)
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (57)
in C:\xampp\htdocs\TrackStar\index.php (13)
2014/03/12 19:58:01 [error] [php] Missing argument 1 for ProjectController::loadModel(), called in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php on line 57 and defined (C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php:164)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ProjectController->run()
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 C:\xampp\htdocs\TrackStar\index.php(13): CWebApplication->run()
REQUEST_URI=/trackstar/index.php?r=project/view&id=1
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (164)
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (57)
in C:\xampp\htdocs\TrackStar\index.php (13)
2014/03/12 19:58:03 [error] [php] Missing argument 1 for ProjectController::loadModel(), called in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php on line 57 and defined (C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php:164)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ProjectController->run()
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 C:\xampp\htdocs\TrackStar\index.php(13): CWebApplication->run()
REQUEST_URI=/trackstar/index.php?r=project/view&id=1
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (164)
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (57)
in C:\xampp\htdocs\TrackStar\index.php (13)
2014/03/12 19:58:05 [error] [php] Missing argument 1 for ProjectController::loadModel(), called in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php on line 57 and defined (C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php:164)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ProjectController->run()
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 C:\xampp\htdocs\TrackStar\index.php(13): CWebApplication->run()
REQUEST_URI=/trackstar/index.php?r=project/view&id=1
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (164)
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (57)
in C:\xampp\htdocs\TrackStar\index.php (13)
2014/03/12 19:59:52 [error] [php] Missing argument 1 for ProjectController::loadModel(), called in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php on line 75 and defined (C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php:181)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ProjectController->run()
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 C:\xampp\htdocs\TrackStar\index.php(13): CWebApplication->run()
REQUEST_URI=/trackstar/index.php?r=project/view&id=1
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (181)
in C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php (75)
in C:\xampp\htdocs\TrackStar\index.php (13)
2014/03/12 20:13:35 [error] [exception.CException] exception 'CException' with message 'Issue and its behaviors do not have a method or closure named "getAttibuteLabel".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:265
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(225): CComponent->__call('getAttibuteLabe...', Array)
#1 C:\xampp\htdocs\TrackStar\protected\views\issue\_view.php(13): CActiveRecord->__call('getAttibuteLabe...', Array)
#2 C:\xampp\htdocs\TrackStar\protected\views\issue\_view.php(13): Issue->getAttibuteLabel('description')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(130): require('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, false)
#5 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(281): CBaseController->renderFile('C:\xampp\htdocs...', Array)
#6 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(160): CListView->renderItems()
#7 [internal function]: CBaseListView->renderSection(Array)
#8 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(143): preg_replace_callback('/{(\w+)}/', Array, '{summary}?{sort...')
#9 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(128): CBaseListView->renderContent()
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(173): CBaseListView->run()
#11 C:\xampp\htdocs\TrackStar\protected\views\issue\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#12 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#14 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#15 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#16 C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php(140): CController->render('index', Array)
#17 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): IssueController->actionIndex()
#18 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#21 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#22 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#24 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#26 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#27 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('issue/index')
#28 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#29 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#30 {main}
REQUEST_URI=/trackstar/index.php?r=issue/index
HTTP_REFERER=http://localhost/trackstar/index.php?r=issue/view&id=1
---
2014/03/12 20:13:57 [error] [exception.CException] exception 'CException' with message 'Issue and its behaviors do not have a method or closure named "getAttibuteLabel".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:265
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(225): CComponent->__call('getAttibuteLabe...', Array)
#1 C:\xampp\htdocs\TrackStar\protected\views\issue\_view.php(13): CActiveRecord->__call('getAttibuteLabe...', Array)
#2 C:\xampp\htdocs\TrackStar\protected\views\issue\_view.php(13): Issue->getAttibuteLabel('description')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(130): require('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, false)
#5 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(281): CBaseController->renderFile('C:\xampp\htdocs...', Array)
#6 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(160): CListView->renderItems()
#7 [internal function]: CBaseListView->renderSection(Array)
#8 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(143): preg_replace_callback('/{(\w+)}/', Array, '{summary}?{sort...')
#9 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(128): CBaseListView->renderContent()
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(173): CBaseListView->run()
#11 C:\xampp\htdocs\TrackStar\protected\views\project\view.php(39): CBaseController->widget('zii.widgets.CLi...', Array)
#12 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#14 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#15 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('view', Array, true)
#16 C:\xampp\htdocs\TrackStar\protected\controllers\ProjectController.php(84): CController->render('view', Array)
#17 [internal function]: ProjectController->actionView('1')
#18 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(ProjectController), Array)
#19 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ProjectController), Object(ReflectionMethod), Array)
#20 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#21 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#22 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#23 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#24 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#25 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#27 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#28 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#29 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('project/view')
#30 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#31 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#32 {main}
REQUEST_URI=/trackstar/index.php?r=project/view&id=1
HTTP_REFERER=http://localhost/trackstar/index.php?r=project
---
2014/03/16 06:33:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested project does not exist.' in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php:206
Stack trace:
#0 C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php(229): IssueController->loadProject(NULL)
#1 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): IssueController->filterProjectContext(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('issue/index')
#11 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#12 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/trackstar/index.php?r=issue/index
HTTP_REFERER=http://localhost/trackstar/index.php?r=issue/view&id=1
---
2014/03/16 06:39:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested project does not exist.' in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php:206
Stack trace:
#0 C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php(229): IssueController->loadProject(NULL)
#1 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): IssueController->filterProjectContext(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('issue/create')
#11 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#12 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/trackstar/index.php?r=issue/create
HTTP_REFERER=http://localhost/trackstar/index.php?r=issue/admin&pid=1
---
2014/04/27 02:41:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trackstar/index.php?r=user
---
2014/04/30 08:23:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TrackStar/index.php?r=user
---
2014/04/30 08:24:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TrackStar/index.php?r=users
---
2014/05/01 08:14:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TrackStar/index.php?r=user
---
2014/05/01 08:14:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "issues".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('issues')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TrackStar/index.php?r=issues
---
2014/05/01 08:14:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested project does not exist.' in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php:206
Stack trace:
#0 C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php(229): IssueController->loadProject(NULL)
#1 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): IssueController->filterProjectContext(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('issue')
#11 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#12 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/TrackStar/index.php?r=issue
---
2014/05/02 07:45:54 [error] [exception.CException] exception 'CException' with message 'Property "User.password_repeat" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(143): CComponent->__get('password_repeat')
#1 C:\xampp\htdocs\yii\framework\validators\CCompareValidator.php(91): CActiveRecord->__get('password_repeat')
#2 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CCompareValidator->validateAttribute(Object(User), 'password')
#3 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(User), NULL)
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(794): CModel->validate(NULL)
#5 C:\xampp\htdocs\TrackStar\protected\controllers\UserController.php(73): CActiveRecord->save()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#16 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#17 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#18 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/TrackStar/index.php?r=user/create
HTTP_REFERER=http://localhost/TrackStar/index.php?r=user/create
---
2014/05/02 07:46:29 [error] [exception.CException] exception 'CException' with message 'Property "User.password_repeat" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(143): CComponent->__get('password_repeat')
#1 C:\xampp\htdocs\yii\framework\validators\CCompareValidator.php(91): CActiveRecord->__get('password_repeat')
#2 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CCompareValidator->validateAttribute(Object(User), 'password')
#3 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(User), NULL)
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(794): CModel->validate(NULL)
#5 C:\xampp\htdocs\TrackStar\protected\controllers\UserController.php(73): CActiveRecord->save()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#16 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#17 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#18 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/TrackStar/index.php?r=user/create
HTTP_REFERER=http://localhost/TrackStar/index.php?r=user/create
---
2014/05/02 07:46:36 [error] [exception.CException] exception 'CException' with message 'Property "User.password_repeat" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(143): CComponent->__get('password_repeat')
#1 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(2255): CActiveRecord->__get('password_repeat')
#2 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(1980): CHtml::resolveValue(Object(User), 'password_repeat')
#3 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(1391): CHtml::activeInputField('password', Object(User), 'password_repeat', Array)
#4 C:\xampp\htdocs\yii\framework\web\widgets\CActiveForm.php(687): CHtml::activePasswordField(Object(User), 'password_repeat', Array)
#5 C:\xampp\htdocs\TrackStar\protected\views\user\_form.php(38): CActiveForm->passwordField(Object(User), 'password_repeat', Array)
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\TrackStar\protected\views\user\create.php(18): CController->renderPartial('_form', Array)
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('create', Array, true)
#14 C:\xampp\htdocs\TrackStar\protected\controllers\UserController.php(79): CController->render('create', Array)
#15 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#17 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#18 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#19 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#20 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#21 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#22 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#23 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#24 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#25 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#26 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#27 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#28 {main}
REQUEST_URI=/TrackStar/index.php?r=user/create
HTTP_REFERER=http://localhost/TrackStar/index.php?r=user/
---
2014/05/02 10:27:42 [error] [exception.CDbException] exception 'CDbException' with message 'No columns are being updated for table "tbl_user".' in C:\xampp\htdocs\yii\framework\db\schema\CDbCommandBuilder.php:290
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1690): CDbCommandBuilder->createUpdateCommand(Object(CMysqlTableSchema), Array, Object(CDbCriteria))
#1 C:\xampp\htdocs\TrackStar\protected\models\LoginForm.php(73): CActiveRecord->updateByPk('8', Array)
#2 C:\xampp\htdocs\TrackStar\protected\controllers\SiteController.php(94): LoginForm->login()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TrackStar/index.php?r=site/login
HTTP_REFERER=http://localhost/TrackStar/index.php?r=site/login
---
2014/05/02 10:29:26 [error] [exception.CDbException] exception 'CDbException' with message 'No columns are being updated for table "tbl_user".' in C:\xampp\htdocs\yii\framework\db\schema\CDbCommandBuilder.php:290
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1690): CDbCommandBuilder->createUpdateCommand(Object(CMysqlTableSchema), Array, Object(CDbCriteria))
#1 C:\xampp\htdocs\TrackStar\protected\models\LoginForm.php(73): CActiveRecord->updateByPk('8', Array)
#2 C:\xampp\htdocs\TrackStar\protected\controllers\SiteController.php(94): LoginForm->login()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TrackStar/index.php?r=site/login
HTTP_REFERER=http://localhost/TrackStar/index.php?r=site/login
---
2014/05/02 10:30:43 [error] [exception.CDbException] exception 'CDbException' with message 'No columns are being updated for table "tbl_user".' in C:\xampp\htdocs\yii\framework\db\schema\CDbCommandBuilder.php:290
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1690): CDbCommandBuilder->createUpdateCommand(Object(CMysqlTableSchema), Array, Object(CDbCriteria))
#1 C:\xampp\htdocs\TrackStar\protected\models\LoginForm.php(73): CActiveRecord->updateByPk('8', Array)
#2 C:\xampp\htdocs\TrackStar\protected\controllers\SiteController.php(94): LoginForm->login()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TrackStar/index.php?r=site/login
HTTP_REFERER=http://localhost/TrackStar/index.php?r=site/login
---
2014/05/03 06:45:13 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.authManager" is read only.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:170
Stack trace:
#0 C:\xampp\htdocs\yii\framework\base\CModule.php(513): CComponent->__set('authManager', Array)
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(150): CModule->configure(Array)
#2 C:\xampp\htdocs\yii\framework\YiiBase.php(125): CApplication->__construct('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\xampp\htdocs...')
#4 C:\xampp\htdocs\TrackStar\index.php(13): YiiBase::createWebApplication('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\yii\framework\cli\commands\ShellCommand.php(78): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\yii\framework\console\CConsoleCommandRunner.php(67): ShellCommand->run(Array)
#7 C:\xampp\htdocs\yii\framework\console\CConsoleApplication.php(91): CConsoleCommandRunner->run(Array)
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CConsoleApplication->processRequest()
#9 C:\xampp\htdocs\yii\framework\yiic.php(33): CApplication->run()
#10 C:\xampp\htdocs\TrackStar\protected\yiic.php(7): require_once('C:\xampp\htdocs...')
#11 {main}
REQUEST_URI=/index.php
---
2014/05/03 06:46:09 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.authManager" is read only.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:170
Stack trace:
#0 C:\xampp\htdocs\yii\framework\base\CModule.php(513): CComponent->__set('authManager', Array)
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(150): CModule->configure(Array)
#2 C:\xampp\htdocs\yii\framework\YiiBase.php(125): CApplication->__construct('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\xampp\htdocs...')
#4 C:\xampp\htdocs\TrackStar\index.php(13): YiiBase::createWebApplication('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\yii\framework\cli\commands\ShellCommand.php(78): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\yii\framework\console\CConsoleCommandRunner.php(67): ShellCommand->run(Array)
#7 C:\xampp\htdocs\yii\framework\console\CConsoleApplication.php(91): CConsoleCommandRunner->run(Array)
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CConsoleApplication->processRequest()
#9 C:\xampp\htdocs\yii\framework\yiic.php(33): CApplication->run()
#10 C:\xampp\htdocs\TrackStar\protected\yiic.php(7): require_once('C:\xampp\htdocs...')
#11 {main}
REQUEST_URI=/index.php
---
2014/05/03 08:45:54 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TrackStar/index.php?r=user/admin
HTTP_REFERER=http://localhost/TrackStar/index.php?r=user/create
---
2014/05/03 08:46:14 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TrackStar/index.php?r=user/admin
HTTP_REFERER=http://localhost/TrackStar/index.php?r=user/index
---
2014/05/03 08:47:22 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('project/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TrackStar/index.php?r=project/admin
HTTP_REFERER=http://localhost/TrackStar/index.php?r=project/create
---
2014/05/03 08:47:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested project does not exist.' in C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php:206
Stack trace:
#0 C:\xampp\htdocs\TrackStar\protected\controllers\IssueController.php(229): IssueController->loadProject(NULL)
#1 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): IssueController->filterProjectContext(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('issue')
#11 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#12 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/TrackStar/index.php?r=issue
---
2014/05/03 08:47:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "issues".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('issues')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TrackStar/index.php?r=issues
---
2014/05/03 08:48:38 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('issue/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TrackStar/index.php?r=issue/admin
HTTP_REFERER=http://localhost/TrackStar/index.php?r=issue/create&pid=1
---
2014/05/03 08:49:56 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('issue/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\TrackStar\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TrackStar/index.php?r=issue/admin
HTTP_REFERER=http://localhost/TrackStar/index.php?r=issue/create&pid=1
---
